// Generated by npm run schema:build; edit schema.json instead.
'use strict';
export const validate = validate10;
export default validate10;
const schema11 = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  required: [
    'id',
    'name',
    'version',
    'format',
    'categories',
    'designWidth',
    'designHeight',
    'slots',
    'textAreas',
    'palette',
    'layers',
    'thumbnail',
    'licenses',
    'description',
  ],
  additionalProperties: false,
  properties: {
    id: { type: 'string', pattern: '^[a-z0-9-]+$' },
    name: { type: 'string', minLength: 1 },
    version: { type: 'integer', minimum: 1 },
    format: { enum: ['strip', 'card'] },
    categories: {
      type: 'array',
      minItems: 1,
      items: {
        enum: [
          'playful',
          'clean',
          'futuristic',
          'soft',
          'cartoon',
          'dynamic',
          'floral',
          'romantic',
          'scrapbook',
          'retro',
          'party',
          'nature',
          'seasonal',
        ],
      },
    },
    description: { type: 'string' },
    collection: { type: 'string', minLength: 1 },
    artwork: {
      type: 'object',
      required: ['motif', 'edition'],
      additionalProperties: false,
      properties: {
        motif: { type: 'string', minLength: 1 },
        edition: { type: 'integer', minimum: 0, maximum: 10 },
      },
    },
    designWidth: { type: 'number', exclusiveMinimum: 0 },
    designHeight: { type: 'number', exclusiveMinimum: 0 },
    slots: {
      type: 'array',
      minItems: 2,
      maxItems: 4,
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'order', 'x', 'y', 'w', 'h', 'shape', 'rotationDeg', 'matteColor'],
        properties: {
          id: { type: 'string', minLength: 1 },
          order: { type: 'integer', minimum: 1, maximum: 4 },
          x: { type: 'number', minimum: 0, maximum: 1 },
          y: { type: 'number', minimum: 0, maximum: 1 },
          w: { type: 'number', exclusiveMinimum: 0, maximum: 1 },
          h: { type: 'number', exclusiveMinimum: 0, maximum: 1 },
          shape: { enum: ['rect', 'roundedRect', 'circle', 'path'] },
          radius: { type: 'number', minimum: 0 },
          pathRef: { enum: ['arch', 'chamfer'] },
          rotationDeg: { type: 'number', minimum: -3, maximum: 3 },
          matteColor: { $ref: '#/definitions/color' },
        },
      },
    },
    textAreas: {
      type: 'array',
      items: {
        type: 'object',
        required: [
          'id',
          'x',
          'y',
          'w',
          'h',
          'fontId',
          'fontSize',
          'minFontSize',
          'maxLines',
          'color',
        ],
        properties: {
          id: { type: 'string' },
          text: { type: 'string' },
          x: { type: 'number', minimum: 0 },
          y: { type: 'number', minimum: 0 },
          w: { type: 'number', exclusiveMinimum: 0 },
          h: { type: 'number', exclusiveMinimum: 0 },
          fontId: { enum: ['sans', 'serif'] },
          fontSize: { type: 'number', exclusiveMinimum: 0 },
          minFontSize: { type: 'number', exclusiveMinimum: 0 },
          maxLines: { type: 'integer', minimum: 1, maximum: 2 },
          color: { $ref: '#/definitions/color' },
        },
      },
    },
    palette: {
      type: 'object',
      required: ['background', 'ink', 'accent', 'secondary'],
      additionalProperties: { $ref: '#/definitions/color' },
    },
    layers: {
      type: 'object',
      required: ['background', 'foreground'],
      properties: { background: { type: 'string' }, foreground: { type: 'string' } },
    },
    thumbnail: { type: 'string' },
    licenses: { type: 'array', minItems: 1, items: { type: 'string' } },
  },
  definitions: { color: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' } },
};
const schema12 = { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' };
const func2 = Object.prototype.hasOwnProperty;
const func3 = (value) => Array.from(value).length;
const pattern0 = new RegExp('^[a-z0-9-]+$', 'u');
const pattern1 = new RegExp('^#[0-9a-fA-F]{6}$', 'u');
function validate10(
  data,
  { instancePath = '', parentData, parentDataProperty, rootData = data } = {},
) {
  let vErrors = null;
  let errors = 0;
  if (data && typeof data == 'object' && !Array.isArray(data)) {
    if (data.id === undefined) {
      const err0 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'id' },
        message: "must have required property '" + 'id' + "'",
      };
      if (vErrors === null) {
        vErrors = [err0];
      } else {
        vErrors.push(err0);
      }
      errors++;
    }
    if (data.name === undefined) {
      const err1 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'name' },
        message: "must have required property '" + 'name' + "'",
      };
      if (vErrors === null) {
        vErrors = [err1];
      } else {
        vErrors.push(err1);
      }
      errors++;
    }
    if (data.version === undefined) {
      const err2 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'version' },
        message: "must have required property '" + 'version' + "'",
      };
      if (vErrors === null) {
        vErrors = [err2];
      } else {
        vErrors.push(err2);
      }
      errors++;
    }
    if (data.format === undefined) {
      const err3 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'format' },
        message: "must have required property '" + 'format' + "'",
      };
      if (vErrors === null) {
        vErrors = [err3];
      } else {
        vErrors.push(err3);
      }
      errors++;
    }
    if (data.categories === undefined) {
      const err4 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'categories' },
        message: "must have required property '" + 'categories' + "'",
      };
      if (vErrors === null) {
        vErrors = [err4];
      } else {
        vErrors.push(err4);
      }
      errors++;
    }
    if (data.designWidth === undefined) {
      const err5 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'designWidth' },
        message: "must have required property '" + 'designWidth' + "'",
      };
      if (vErrors === null) {
        vErrors = [err5];
      } else {
        vErrors.push(err5);
      }
      errors++;
    }
    if (data.designHeight === undefined) {
      const err6 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'designHeight' },
        message: "must have required property '" + 'designHeight' + "'",
      };
      if (vErrors === null) {
        vErrors = [err6];
      } else {
        vErrors.push(err6);
      }
      errors++;
    }
    if (data.slots === undefined) {
      const err7 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'slots' },
        message: "must have required property '" + 'slots' + "'",
      };
      if (vErrors === null) {
        vErrors = [err7];
      } else {
        vErrors.push(err7);
      }
      errors++;
    }
    if (data.textAreas === undefined) {
      const err8 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'textAreas' },
        message: "must have required property '" + 'textAreas' + "'",
      };
      if (vErrors === null) {
        vErrors = [err8];
      } else {
        vErrors.push(err8);
      }
      errors++;
    }
    if (data.palette === undefined) {
      const err9 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'palette' },
        message: "must have required property '" + 'palette' + "'",
      };
      if (vErrors === null) {
        vErrors = [err9];
      } else {
        vErrors.push(err9);
      }
      errors++;
    }
    if (data.layers === undefined) {
      const err10 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'layers' },
        message: "must have required property '" + 'layers' + "'",
      };
      if (vErrors === null) {
        vErrors = [err10];
      } else {
        vErrors.push(err10);
      }
      errors++;
    }
    if (data.thumbnail === undefined) {
      const err11 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'thumbnail' },
        message: "must have required property '" + 'thumbnail' + "'",
      };
      if (vErrors === null) {
        vErrors = [err11];
      } else {
        vErrors.push(err11);
      }
      errors++;
    }
    if (data.licenses === undefined) {
      const err12 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'licenses' },
        message: "must have required property '" + 'licenses' + "'",
      };
      if (vErrors === null) {
        vErrors = [err12];
      } else {
        vErrors.push(err12);
      }
      errors++;
    }
    if (data.description === undefined) {
      const err13 = {
        instancePath,
        schemaPath: '#/required',
        keyword: 'required',
        params: { missingProperty: 'description' },
        message: "must have required property '" + 'description' + "'",
      };
      if (vErrors === null) {
        vErrors = [err13];
      } else {
        vErrors.push(err13);
      }
      errors++;
    }
    for (const key0 in data) {
      if (!func2.call(schema11.properties, key0)) {
        const err14 = {
          instancePath,
          schemaPath: '#/additionalProperties',
          keyword: 'additionalProperties',
          params: { additionalProperty: key0 },
          message: 'must NOT have additional properties',
        };
        if (vErrors === null) {
          vErrors = [err14];
        } else {
          vErrors.push(err14);
        }
        errors++;
      }
    }
    if (data.id !== undefined) {
      let data0 = data.id;
      if (typeof data0 === 'string') {
        if (!pattern0.test(data0)) {
          const err15 = {
            instancePath: instancePath + '/id',
            schemaPath: '#/properties/id/pattern',
            keyword: 'pattern',
            params: { pattern: '^[a-z0-9-]+$' },
            message: 'must match pattern "' + '^[a-z0-9-]+$' + '"',
          };
          if (vErrors === null) {
            vErrors = [err15];
          } else {
            vErrors.push(err15);
          }
          errors++;
        }
      } else {
        const err16 = {
          instancePath: instancePath + '/id',
          schemaPath: '#/properties/id/type',
          keyword: 'type',
          params: { type: 'string' },
          message: 'must be string',
        };
        if (vErrors === null) {
          vErrors = [err16];
        } else {
          vErrors.push(err16);
        }
        errors++;
      }
    }
    if (data.name !== undefined) {
      let data1 = data.name;
      if (typeof data1 === 'string') {
        if (func3(data1) < 1) {
          const err17 = {
            instancePath: instancePath + '/name',
            schemaPath: '#/properties/name/minLength',
            keyword: 'minLength',
            params: { limit: 1 },
            message: 'must NOT have fewer than 1 characters',
          };
          if (vErrors === null) {
            vErrors = [err17];
          } else {
            vErrors.push(err17);
          }
          errors++;
        }
      } else {
        const err18 = {
          instancePath: instancePath + '/name',
          schemaPath: '#/properties/name/type',
          keyword: 'type',
          params: { type: 'string' },
          message: 'must be string',
        };
        if (vErrors === null) {
          vErrors = [err18];
        } else {
          vErrors.push(err18);
        }
        errors++;
      }
    }
    if (data.version !== undefined) {
      let data2 = data.version;
      if (!(typeof data2 == 'number' && !(data2 % 1) && !isNaN(data2))) {
        const err19 = {
          instancePath: instancePath + '/version',
          schemaPath: '#/properties/version/type',
          keyword: 'type',
          params: { type: 'integer' },
          message: 'must be integer',
        };
        if (vErrors === null) {
          vErrors = [err19];
        } else {
          vErrors.push(err19);
        }
        errors++;
      }
      if (typeof data2 == 'number') {
        if (data2 < 1 || isNaN(data2)) {
          const err20 = {
            instancePath: instancePath + '/version',
            schemaPath: '#/properties/version/minimum',
            keyword: 'minimum',
            params: { comparison: '>=', limit: 1 },
            message: 'must be >= 1',
          };
          if (vErrors === null) {
            vErrors = [err20];
          } else {
            vErrors.push(err20);
          }
          errors++;
        }
      }
    }
    if (data.format !== undefined) {
      let data3 = data.format;
      if (!(data3 === 'strip' || data3 === 'card')) {
        const err21 = {
          instancePath: instancePath + '/format',
          schemaPath: '#/properties/format/enum',
          keyword: 'enum',
          params: { allowedValues: schema11.properties.format.enum },
          message: 'must be equal to one of the allowed values',
        };
        if (vErrors === null) {
          vErrors = [err21];
        } else {
          vErrors.push(err21);
        }
        errors++;
      }
    }
    if (data.categories !== undefined) {
      let data4 = data.categories;
      if (Array.isArray(data4)) {
        if (data4.length < 1) {
          const err22 = {
            instancePath: instancePath + '/categories',
            schemaPath: '#/properties/categories/minItems',
            keyword: 'minItems',
            params: { limit: 1 },
            message: 'must NOT have fewer than 1 items',
          };
          if (vErrors === null) {
            vErrors = [err22];
          } else {
            vErrors.push(err22);
          }
          errors++;
        }
        const len0 = data4.length;
        for (let i0 = 0; i0 < len0; i0++) {
          let data5 = data4[i0];
          if (!(
            data5 === 'playful' ||
            data5 === 'clean' ||
            data5 === 'futuristic' ||
            data5 === 'soft' ||
            data5 === 'cartoon' ||
            data5 === 'dynamic' ||
            data5 === 'floral' ||
            data5 === 'romantic' ||
            data5 === 'scrapbook' ||
            data5 === 'retro' ||
            data5 === 'party' ||
            data5 === 'nature' ||
            data5 === 'seasonal'
          )) {
            const err23 = {
              instancePath: instancePath + '/categories/' + i0,
              schemaPath: '#/properties/categories/items/enum',
              keyword: 'enum',
              params: { allowedValues: schema11.properties.categories.items.enum },
              message: 'must be equal to one of the allowed values',
            };
            if (vErrors === null) {
              vErrors = [err23];
            } else {
              vErrors.push(err23);
            }
            errors++;
          }
        }
      } else {
        const err24 = {
          instancePath: instancePath + '/categories',
          schemaPath: '#/properties/categories/type',
          keyword: 'type',
          params: { type: 'array' },
          message: 'must be array',
        };
        if (vErrors === null) {
          vErrors = [err24];
        } else {
          vErrors.push(err24);
        }
        errors++;
      }
    }
    if (data.description !== undefined) {
      if (typeof data.description !== 'string') {
        const err25 = {
          instancePath: instancePath + '/description',
          schemaPath: '#/properties/description/type',
          keyword: 'type',
          params: { type: 'string' },
          message: 'must be string',
        };
        if (vErrors === null) {
          vErrors = [err25];
        } else {
          vErrors.push(err25);
        }
        errors++;
      }
    }
    if (data.collection !== undefined) {
      let data7 = data.collection;
      if (typeof data7 === 'string') {
        if (func3(data7) < 1) {
          const err26 = {
            instancePath: instancePath + '/collection',
            schemaPath: '#/properties/collection/minLength',
            keyword: 'minLength',
            params: { limit: 1 },
            message: 'must NOT have fewer than 1 characters',
          };
          if (vErrors === null) {
            vErrors = [err26];
          } else {
            vErrors.push(err26);
          }
          errors++;
        }
      } else {
        const err27 = {
          instancePath: instancePath + '/collection',
          schemaPath: '#/properties/collection/type',
          keyword: 'type',
          params: { type: 'string' },
          message: 'must be string',
        };
        if (vErrors === null) {
          vErrors = [err27];
        } else {
          vErrors.push(err27);
        }
        errors++;
      }
    }
    if (data.artwork !== undefined) {
      let data8 = data.artwork;
      if (data8 && typeof data8 == 'object' && !Array.isArray(data8)) {
        if (data8.motif === undefined) {
          const err28 = {
            instancePath: instancePath + '/artwork',
            schemaPath: '#/properties/artwork/required',
            keyword: 'required',
            params: { missingProperty: 'motif' },
            message: "must have required property '" + 'motif' + "'",
          };
          if (vErrors === null) {
            vErrors = [err28];
          } else {
            vErrors.push(err28);
          }
          errors++;
        }
        if (data8.edition === undefined) {
          const err29 = {
            instancePath: instancePath + '/artwork',
            schemaPath: '#/properties/artwork/required',
            keyword: 'required',
            params: { missingProperty: 'edition' },
            message: "must have required property '" + 'edition' + "'",
          };
          if (vErrors === null) {
            vErrors = [err29];
          } else {
            vErrors.push(err29);
          }
          errors++;
        }
        for (const key1 in data8) {
          if (!(key1 === 'motif' || key1 === 'edition')) {
            const err30 = {
              instancePath: instancePath + '/artwork',
              schemaPath: '#/properties/artwork/additionalProperties',
              keyword: 'additionalProperties',
              params: { additionalProperty: key1 },
              message: 'must NOT have additional properties',
            };
            if (vErrors === null) {
              vErrors = [err30];
            } else {
              vErrors.push(err30);
            }
            errors++;
          }
        }
        if (data8.motif !== undefined) {
          let data9 = data8.motif;
          if (typeof data9 === 'string') {
            if (func3(data9) < 1) {
              const err31 = {
                instancePath: instancePath + '/artwork/motif',
                schemaPath: '#/properties/artwork/properties/motif/minLength',
                keyword: 'minLength',
                params: { limit: 1 },
                message: 'must NOT have fewer than 1 characters',
              };
              if (vErrors === null) {
                vErrors = [err31];
              } else {
                vErrors.push(err31);
              }
              errors++;
            }
          } else {
            const err32 = {
              instancePath: instancePath + '/artwork/motif',
              schemaPath: '#/properties/artwork/properties/motif/type',
              keyword: 'type',
              params: { type: 'string' },
              message: 'must be string',
            };
            if (vErrors === null) {
              vErrors = [err32];
            } else {
              vErrors.push(err32);
            }
            errors++;
          }
        }
        if (data8.edition !== undefined) {
          let data10 = data8.edition;
          if (!(typeof data10 == 'number' && !(data10 % 1) && !isNaN(data10))) {
            const err33 = {
              instancePath: instancePath + '/artwork/edition',
              schemaPath: '#/properties/artwork/properties/edition/type',
              keyword: 'type',
              params: { type: 'integer' },
              message: 'must be integer',
            };
            if (vErrors === null) {
              vErrors = [err33];
            } else {
              vErrors.push(err33);
            }
            errors++;
          }
          if (typeof data10 == 'number') {
            if (data10 > 10 || isNaN(data10)) {
              const err34 = {
                instancePath: instancePath + '/artwork/edition',
                schemaPath: '#/properties/artwork/properties/edition/maximum',
                keyword: 'maximum',
                params: { comparison: '<=', limit: 10 },
                message: 'must be <= 10',
              };
              if (vErrors === null) {
                vErrors = [err34];
              } else {
                vErrors.push(err34);
              }
              errors++;
            }
            if (data10 < 0 || isNaN(data10)) {
              const err35 = {
                instancePath: instancePath + '/artwork/edition',
                schemaPath: '#/properties/artwork/properties/edition/minimum',
                keyword: 'minimum',
                params: { comparison: '>=', limit: 0 },
                message: 'must be >= 0',
              };
              if (vErrors === null) {
                vErrors = [err35];
              } else {
                vErrors.push(err35);
              }
              errors++;
            }
          }
        }
      } else {
        const err36 = {
          instancePath: instancePath + '/artwork',
          schemaPath: '#/properties/artwork/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        };
        if (vErrors === null) {
          vErrors = [err36];
        } else {
          vErrors.push(err36);
        }
        errors++;
      }
    }
    if (data.designWidth !== undefined) {
      let data11 = data.designWidth;
      if (typeof data11 == 'number') {
        if (data11 <= 0 || isNaN(data11)) {
          const err37 = {
            instancePath: instancePath + '/designWidth',
            schemaPath: '#/properties/designWidth/exclusiveMinimum',
            keyword: 'exclusiveMinimum',
            params: { comparison: '>', limit: 0 },
            message: 'must be > 0',
          };
          if (vErrors === null) {
            vErrors = [err37];
          } else {
            vErrors.push(err37);
          }
          errors++;
        }
      } else {
        const err38 = {
          instancePath: instancePath + '/designWidth',
          schemaPath: '#/properties/designWidth/type',
          keyword: 'type',
          params: { type: 'number' },
          message: 'must be number',
        };
        if (vErrors === null) {
          vErrors = [err38];
        } else {
          vErrors.push(err38);
        }
        errors++;
      }
    }
    if (data.designHeight !== undefined) {
      let data12 = data.designHeight;
      if (typeof data12 == 'number') {
        if (data12 <= 0 || isNaN(data12)) {
          const err39 = {
            instancePath: instancePath + '/designHeight',
            schemaPath: '#/properties/designHeight/exclusiveMinimum',
            keyword: 'exclusiveMinimum',
            params: { comparison: '>', limit: 0 },
            message: 'must be > 0',
          };
          if (vErrors === null) {
            vErrors = [err39];
          } else {
            vErrors.push(err39);
          }
          errors++;
        }
      } else {
        const err40 = {
          instancePath: instancePath + '/designHeight',
          schemaPath: '#/properties/designHeight/type',
          keyword: 'type',
          params: { type: 'number' },
          message: 'must be number',
        };
        if (vErrors === null) {
          vErrors = [err40];
        } else {
          vErrors.push(err40);
        }
        errors++;
      }
    }
    if (data.slots !== undefined) {
      let data13 = data.slots;
      if (Array.isArray(data13)) {
        if (data13.length > 4) {
          const err41 = {
            instancePath: instancePath + '/slots',
            schemaPath: '#/properties/slots/maxItems',
            keyword: 'maxItems',
            params: { limit: 4 },
            message: 'must NOT have more than 4 items',
          };
          if (vErrors === null) {
            vErrors = [err41];
          } else {
            vErrors.push(err41);
          }
          errors++;
        }
        if (data13.length < 2) {
          const err42 = {
            instancePath: instancePath + '/slots',
            schemaPath: '#/properties/slots/minItems',
            keyword: 'minItems',
            params: { limit: 2 },
            message: 'must NOT have fewer than 2 items',
          };
          if (vErrors === null) {
            vErrors = [err42];
          } else {
            vErrors.push(err42);
          }
          errors++;
        }
        const len1 = data13.length;
        for (let i1 = 0; i1 < len1; i1++) {
          let data14 = data13[i1];
          if (data14 && typeof data14 == 'object' && !Array.isArray(data14)) {
            if (data14.id === undefined) {
              const err43 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'id' },
                message: "must have required property '" + 'id' + "'",
              };
              if (vErrors === null) {
                vErrors = [err43];
              } else {
                vErrors.push(err43);
              }
              errors++;
            }
            if (data14.order === undefined) {
              const err44 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'order' },
                message: "must have required property '" + 'order' + "'",
              };
              if (vErrors === null) {
                vErrors = [err44];
              } else {
                vErrors.push(err44);
              }
              errors++;
            }
            if (data14.x === undefined) {
              const err45 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'x' },
                message: "must have required property '" + 'x' + "'",
              };
              if (vErrors === null) {
                vErrors = [err45];
              } else {
                vErrors.push(err45);
              }
              errors++;
            }
            if (data14.y === undefined) {
              const err46 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'y' },
                message: "must have required property '" + 'y' + "'",
              };
              if (vErrors === null) {
                vErrors = [err46];
              } else {
                vErrors.push(err46);
              }
              errors++;
            }
            if (data14.w === undefined) {
              const err47 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'w' },
                message: "must have required property '" + 'w' + "'",
              };
              if (vErrors === null) {
                vErrors = [err47];
              } else {
                vErrors.push(err47);
              }
              errors++;
            }
            if (data14.h === undefined) {
              const err48 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'h' },
                message: "must have required property '" + 'h' + "'",
              };
              if (vErrors === null) {
                vErrors = [err48];
              } else {
                vErrors.push(err48);
              }
              errors++;
            }
            if (data14.shape === undefined) {
              const err49 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'shape' },
                message: "must have required property '" + 'shape' + "'",
              };
              if (vErrors === null) {
                vErrors = [err49];
              } else {
                vErrors.push(err49);
              }
              errors++;
            }
            if (data14.rotationDeg === undefined) {
              const err50 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'rotationDeg' },
                message: "must have required property '" + 'rotationDeg' + "'",
              };
              if (vErrors === null) {
                vErrors = [err50];
              } else {
                vErrors.push(err50);
              }
              errors++;
            }
            if (data14.matteColor === undefined) {
              const err51 = {
                instancePath: instancePath + '/slots/' + i1,
                schemaPath: '#/properties/slots/items/required',
                keyword: 'required',
                params: { missingProperty: 'matteColor' },
                message: "must have required property '" + 'matteColor' + "'",
              };
              if (vErrors === null) {
                vErrors = [err51];
              } else {
                vErrors.push(err51);
              }
              errors++;
            }
            for (const key2 in data14) {
              if (!func2.call(schema11.properties.slots.items.properties, key2)) {
                const err52 = {
                  instancePath: instancePath + '/slots/' + i1,
                  schemaPath: '#/properties/slots/items/additionalProperties',
                  keyword: 'additionalProperties',
                  params: { additionalProperty: key2 },
                  message: 'must NOT have additional properties',
                };
                if (vErrors === null) {
                  vErrors = [err52];
                } else {
                  vErrors.push(err52);
                }
                errors++;
              }
            }
            if (data14.id !== undefined) {
              let data15 = data14.id;
              if (typeof data15 === 'string') {
                if (func3(data15) < 1) {
                  const err53 = {
                    instancePath: instancePath + '/slots/' + i1 + '/id',
                    schemaPath: '#/properties/slots/items/properties/id/minLength',
                    keyword: 'minLength',
                    params: { limit: 1 },
                    message: 'must NOT have fewer than 1 characters',
                  };
                  if (vErrors === null) {
                    vErrors = [err53];
                  } else {
                    vErrors.push(err53);
                  }
                  errors++;
                }
              } else {
                const err54 = {
                  instancePath: instancePath + '/slots/' + i1 + '/id',
                  schemaPath: '#/properties/slots/items/properties/id/type',
                  keyword: 'type',
                  params: { type: 'string' },
                  message: 'must be string',
                };
                if (vErrors === null) {
                  vErrors = [err54];
                } else {
                  vErrors.push(err54);
                }
                errors++;
              }
            }
            if (data14.order !== undefined) {
              let data16 = data14.order;
              if (!(typeof data16 == 'number' && !(data16 % 1) && !isNaN(data16))) {
                const err55 = {
                  instancePath: instancePath + '/slots/' + i1 + '/order',
                  schemaPath: '#/properties/slots/items/properties/order/type',
                  keyword: 'type',
                  params: { type: 'integer' },
                  message: 'must be integer',
                };
                if (vErrors === null) {
                  vErrors = [err55];
                } else {
                  vErrors.push(err55);
                }
                errors++;
              }
              if (typeof data16 == 'number') {
                if (data16 > 4 || isNaN(data16)) {
                  const err56 = {
                    instancePath: instancePath + '/slots/' + i1 + '/order',
                    schemaPath: '#/properties/slots/items/properties/order/maximum',
                    keyword: 'maximum',
                    params: { comparison: '<=', limit: 4 },
                    message: 'must be <= 4',
                  };
                  if (vErrors === null) {
                    vErrors = [err56];
                  } else {
                    vErrors.push(err56);
                  }
                  errors++;
                }
                if (data16 < 1 || isNaN(data16)) {
                  const err57 = {
                    instancePath: instancePath + '/slots/' + i1 + '/order',
                    schemaPath: '#/properties/slots/items/properties/order/minimum',
                    keyword: 'minimum',
                    params: { comparison: '>=', limit: 1 },
                    message: 'must be >= 1',
                  };
                  if (vErrors === null) {
                    vErrors = [err57];
                  } else {
                    vErrors.push(err57);
                  }
                  errors++;
                }
              }
            }
            if (data14.x !== undefined) {
              let data17 = data14.x;
              if (typeof data17 == 'number') {
                if (data17 > 1 || isNaN(data17)) {
                  const err58 = {
                    instancePath: instancePath + '/slots/' + i1 + '/x',
                    schemaPath: '#/properties/slots/items/properties/x/maximum',
                    keyword: 'maximum',
                    params: { comparison: '<=', limit: 1 },
                    message: 'must be <= 1',
                  };
                  if (vErrors === null) {
                    vErrors = [err58];
                  } else {
                    vErrors.push(err58);
                  }
                  errors++;
                }
                if (data17 < 0 || isNaN(data17)) {
                  const err59 = {
                    instancePath: instancePath + '/slots/' + i1 + '/x',
                    schemaPath: '#/properties/slots/items/properties/x/minimum',
                    keyword: 'minimum',
                    params: { comparison: '>=', limit: 0 },
                    message: 'must be >= 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err59];
                  } else {
                    vErrors.push(err59);
                  }
                  errors++;
                }
              } else {
                const err60 = {
                  instancePath: instancePath + '/slots/' + i1 + '/x',
                  schemaPath: '#/properties/slots/items/properties/x/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err60];
                } else {
                  vErrors.push(err60);
                }
                errors++;
              }
            }
            if (data14.y !== undefined) {
              let data18 = data14.y;
              if (typeof data18 == 'number') {
                if (data18 > 1 || isNaN(data18)) {
                  const err61 = {
                    instancePath: instancePath + '/slots/' + i1 + '/y',
                    schemaPath: '#/properties/slots/items/properties/y/maximum',
                    keyword: 'maximum',
                    params: { comparison: '<=', limit: 1 },
                    message: 'must be <= 1',
                  };
                  if (vErrors === null) {
                    vErrors = [err61];
                  } else {
                    vErrors.push(err61);
                  }
                  errors++;
                }
                if (data18 < 0 || isNaN(data18)) {
                  const err62 = {
                    instancePath: instancePath + '/slots/' + i1 + '/y',
                    schemaPath: '#/properties/slots/items/properties/y/minimum',
                    keyword: 'minimum',
                    params: { comparison: '>=', limit: 0 },
                    message: 'must be >= 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err62];
                  } else {
                    vErrors.push(err62);
                  }
                  errors++;
                }
              } else {
                const err63 = {
                  instancePath: instancePath + '/slots/' + i1 + '/y',
                  schemaPath: '#/properties/slots/items/properties/y/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err63];
                } else {
                  vErrors.push(err63);
                }
                errors++;
              }
            }
            if (data14.w !== undefined) {
              let data19 = data14.w;
              if (typeof data19 == 'number') {
                if (data19 > 1 || isNaN(data19)) {
                  const err64 = {
                    instancePath: instancePath + '/slots/' + i1 + '/w',
                    schemaPath: '#/properties/slots/items/properties/w/maximum',
                    keyword: 'maximum',
                    params: { comparison: '<=', limit: 1 },
                    message: 'must be <= 1',
                  };
                  if (vErrors === null) {
                    vErrors = [err64];
                  } else {
                    vErrors.push(err64);
                  }
                  errors++;
                }
                if (data19 <= 0 || isNaN(data19)) {
                  const err65 = {
                    instancePath: instancePath + '/slots/' + i1 + '/w',
                    schemaPath: '#/properties/slots/items/properties/w/exclusiveMinimum',
                    keyword: 'exclusiveMinimum',
                    params: { comparison: '>', limit: 0 },
                    message: 'must be > 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err65];
                  } else {
                    vErrors.push(err65);
                  }
                  errors++;
                }
              } else {
                const err66 = {
                  instancePath: instancePath + '/slots/' + i1 + '/w',
                  schemaPath: '#/properties/slots/items/properties/w/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err66];
                } else {
                  vErrors.push(err66);
                }
                errors++;
              }
            }
            if (data14.h !== undefined) {
              let data20 = data14.h;
              if (typeof data20 == 'number') {
                if (data20 > 1 || isNaN(data20)) {
                  const err67 = {
                    instancePath: instancePath + '/slots/' + i1 + '/h',
                    schemaPath: '#/properties/slots/items/properties/h/maximum',
                    keyword: 'maximum',
                    params: { comparison: '<=', limit: 1 },
                    message: 'must be <= 1',
                  };
                  if (vErrors === null) {
                    vErrors = [err67];
                  } else {
                    vErrors.push(err67);
                  }
                  errors++;
                }
                if (data20 <= 0 || isNaN(data20)) {
                  const err68 = {
                    instancePath: instancePath + '/slots/' + i1 + '/h',
                    schemaPath: '#/properties/slots/items/properties/h/exclusiveMinimum',
                    keyword: 'exclusiveMinimum',
                    params: { comparison: '>', limit: 0 },
                    message: 'must be > 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err68];
                  } else {
                    vErrors.push(err68);
                  }
                  errors++;
                }
              } else {
                const err69 = {
                  instancePath: instancePath + '/slots/' + i1 + '/h',
                  schemaPath: '#/properties/slots/items/properties/h/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err69];
                } else {
                  vErrors.push(err69);
                }
                errors++;
              }
            }
            if (data14.shape !== undefined) {
              let data21 = data14.shape;
              if (!(
                data21 === 'rect' ||
                data21 === 'roundedRect' ||
                data21 === 'circle' ||
                data21 === 'path'
              )) {
                const err70 = {
                  instancePath: instancePath + '/slots/' + i1 + '/shape',
                  schemaPath: '#/properties/slots/items/properties/shape/enum',
                  keyword: 'enum',
                  params: { allowedValues: schema11.properties.slots.items.properties.shape.enum },
                  message: 'must be equal to one of the allowed values',
                };
                if (vErrors === null) {
                  vErrors = [err70];
                } else {
                  vErrors.push(err70);
                }
                errors++;
              }
            }
            if (data14.radius !== undefined) {
              let data22 = data14.radius;
              if (typeof data22 == 'number') {
                if (data22 < 0 || isNaN(data22)) {
                  const err71 = {
                    instancePath: instancePath + '/slots/' + i1 + '/radius',
                    schemaPath: '#/properties/slots/items/properties/radius/minimum',
                    keyword: 'minimum',
                    params: { comparison: '>=', limit: 0 },
                    message: 'must be >= 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err71];
                  } else {
                    vErrors.push(err71);
                  }
                  errors++;
                }
              } else {
                const err72 = {
                  instancePath: instancePath + '/slots/' + i1 + '/radius',
                  schemaPath: '#/properties/slots/items/properties/radius/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err72];
                } else {
                  vErrors.push(err72);
                }
                errors++;
              }
            }
            if (data14.pathRef !== undefined) {
              let data23 = data14.pathRef;
              if (!(data23 === 'arch' || data23 === 'chamfer')) {
                const err73 = {
                  instancePath: instancePath + '/slots/' + i1 + '/pathRef',
                  schemaPath: '#/properties/slots/items/properties/pathRef/enum',
                  keyword: 'enum',
                  params: {
                    allowedValues: schema11.properties.slots.items.properties.pathRef.enum,
                  },
                  message: 'must be equal to one of the allowed values',
                };
                if (vErrors === null) {
                  vErrors = [err73];
                } else {
                  vErrors.push(err73);
                }
                errors++;
              }
            }
            if (data14.rotationDeg !== undefined) {
              let data24 = data14.rotationDeg;
              if (typeof data24 == 'number') {
                if (data24 > 3 || isNaN(data24)) {
                  const err74 = {
                    instancePath: instancePath + '/slots/' + i1 + '/rotationDeg',
                    schemaPath: '#/properties/slots/items/properties/rotationDeg/maximum',
                    keyword: 'maximum',
                    params: { comparison: '<=', limit: 3 },
                    message: 'must be <= 3',
                  };
                  if (vErrors === null) {
                    vErrors = [err74];
                  } else {
                    vErrors.push(err74);
                  }
                  errors++;
                }
                if (data24 < -3 || isNaN(data24)) {
                  const err75 = {
                    instancePath: instancePath + '/slots/' + i1 + '/rotationDeg',
                    schemaPath: '#/properties/slots/items/properties/rotationDeg/minimum',
                    keyword: 'minimum',
                    params: { comparison: '>=', limit: -3 },
                    message: 'must be >= -3',
                  };
                  if (vErrors === null) {
                    vErrors = [err75];
                  } else {
                    vErrors.push(err75);
                  }
                  errors++;
                }
              } else {
                const err76 = {
                  instancePath: instancePath + '/slots/' + i1 + '/rotationDeg',
                  schemaPath: '#/properties/slots/items/properties/rotationDeg/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err76];
                } else {
                  vErrors.push(err76);
                }
                errors++;
              }
            }
            if (data14.matteColor !== undefined) {
              let data25 = data14.matteColor;
              if (typeof data25 === 'string') {
                if (!pattern1.test(data25)) {
                  const err77 = {
                    instancePath: instancePath + '/slots/' + i1 + '/matteColor',
                    schemaPath: '#/definitions/color/pattern',
                    keyword: 'pattern',
                    params: { pattern: '^#[0-9a-fA-F]{6}$' },
                    message: 'must match pattern "' + '^#[0-9a-fA-F]{6}$' + '"',
                  };
                  if (vErrors === null) {
                    vErrors = [err77];
                  } else {
                    vErrors.push(err77);
                  }
                  errors++;
                }
              } else {
                const err78 = {
                  instancePath: instancePath + '/slots/' + i1 + '/matteColor',
                  schemaPath: '#/definitions/color/type',
                  keyword: 'type',
                  params: { type: 'string' },
                  message: 'must be string',
                };
                if (vErrors === null) {
                  vErrors = [err78];
                } else {
                  vErrors.push(err78);
                }
                errors++;
              }
            }
          } else {
            const err79 = {
              instancePath: instancePath + '/slots/' + i1,
              schemaPath: '#/properties/slots/items/type',
              keyword: 'type',
              params: { type: 'object' },
              message: 'must be object',
            };
            if (vErrors === null) {
              vErrors = [err79];
            } else {
              vErrors.push(err79);
            }
            errors++;
          }
        }
      } else {
        const err80 = {
          instancePath: instancePath + '/slots',
          schemaPath: '#/properties/slots/type',
          keyword: 'type',
          params: { type: 'array' },
          message: 'must be array',
        };
        if (vErrors === null) {
          vErrors = [err80];
        } else {
          vErrors.push(err80);
        }
        errors++;
      }
    }
    if (data.textAreas !== undefined) {
      let data26 = data.textAreas;
      if (Array.isArray(data26)) {
        const len2 = data26.length;
        for (let i2 = 0; i2 < len2; i2++) {
          let data27 = data26[i2];
          if (data27 && typeof data27 == 'object' && !Array.isArray(data27)) {
            if (data27.id === undefined) {
              const err81 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'id' },
                message: "must have required property '" + 'id' + "'",
              };
              if (vErrors === null) {
                vErrors = [err81];
              } else {
                vErrors.push(err81);
              }
              errors++;
            }
            if (data27.x === undefined) {
              const err82 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'x' },
                message: "must have required property '" + 'x' + "'",
              };
              if (vErrors === null) {
                vErrors = [err82];
              } else {
                vErrors.push(err82);
              }
              errors++;
            }
            if (data27.y === undefined) {
              const err83 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'y' },
                message: "must have required property '" + 'y' + "'",
              };
              if (vErrors === null) {
                vErrors = [err83];
              } else {
                vErrors.push(err83);
              }
              errors++;
            }
            if (data27.w === undefined) {
              const err84 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'w' },
                message: "must have required property '" + 'w' + "'",
              };
              if (vErrors === null) {
                vErrors = [err84];
              } else {
                vErrors.push(err84);
              }
              errors++;
            }
            if (data27.h === undefined) {
              const err85 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'h' },
                message: "must have required property '" + 'h' + "'",
              };
              if (vErrors === null) {
                vErrors = [err85];
              } else {
                vErrors.push(err85);
              }
              errors++;
            }
            if (data27.fontId === undefined) {
              const err86 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'fontId' },
                message: "must have required property '" + 'fontId' + "'",
              };
              if (vErrors === null) {
                vErrors = [err86];
              } else {
                vErrors.push(err86);
              }
              errors++;
            }
            if (data27.fontSize === undefined) {
              const err87 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'fontSize' },
                message: "must have required property '" + 'fontSize' + "'",
              };
              if (vErrors === null) {
                vErrors = [err87];
              } else {
                vErrors.push(err87);
              }
              errors++;
            }
            if (data27.minFontSize === undefined) {
              const err88 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'minFontSize' },
                message: "must have required property '" + 'minFontSize' + "'",
              };
              if (vErrors === null) {
                vErrors = [err88];
              } else {
                vErrors.push(err88);
              }
              errors++;
            }
            if (data27.maxLines === undefined) {
              const err89 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'maxLines' },
                message: "must have required property '" + 'maxLines' + "'",
              };
              if (vErrors === null) {
                vErrors = [err89];
              } else {
                vErrors.push(err89);
              }
              errors++;
            }
            if (data27.color === undefined) {
              const err90 = {
                instancePath: instancePath + '/textAreas/' + i2,
                schemaPath: '#/properties/textAreas/items/required',
                keyword: 'required',
                params: { missingProperty: 'color' },
                message: "must have required property '" + 'color' + "'",
              };
              if (vErrors === null) {
                vErrors = [err90];
              } else {
                vErrors.push(err90);
              }
              errors++;
            }
            if (data27.id !== undefined) {
              if (typeof data27.id !== 'string') {
                const err91 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/id',
                  schemaPath: '#/properties/textAreas/items/properties/id/type',
                  keyword: 'type',
                  params: { type: 'string' },
                  message: 'must be string',
                };
                if (vErrors === null) {
                  vErrors = [err91];
                } else {
                  vErrors.push(err91);
                }
                errors++;
              }
            }
            if (data27.text !== undefined) {
              if (typeof data27.text !== 'string') {
                const err92 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/text',
                  schemaPath: '#/properties/textAreas/items/properties/text/type',
                  keyword: 'type',
                  params: { type: 'string' },
                  message: 'must be string',
                };
                if (vErrors === null) {
                  vErrors = [err92];
                } else {
                  vErrors.push(err92);
                }
                errors++;
              }
            }
            if (data27.x !== undefined) {
              let data30 = data27.x;
              if (typeof data30 == 'number') {
                if (data30 < 0 || isNaN(data30)) {
                  const err93 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/x',
                    schemaPath: '#/properties/textAreas/items/properties/x/minimum',
                    keyword: 'minimum',
                    params: { comparison: '>=', limit: 0 },
                    message: 'must be >= 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err93];
                  } else {
                    vErrors.push(err93);
                  }
                  errors++;
                }
              } else {
                const err94 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/x',
                  schemaPath: '#/properties/textAreas/items/properties/x/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err94];
                } else {
                  vErrors.push(err94);
                }
                errors++;
              }
            }
            if (data27.y !== undefined) {
              let data31 = data27.y;
              if (typeof data31 == 'number') {
                if (data31 < 0 || isNaN(data31)) {
                  const err95 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/y',
                    schemaPath: '#/properties/textAreas/items/properties/y/minimum',
                    keyword: 'minimum',
                    params: { comparison: '>=', limit: 0 },
                    message: 'must be >= 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err95];
                  } else {
                    vErrors.push(err95);
                  }
                  errors++;
                }
              } else {
                const err96 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/y',
                  schemaPath: '#/properties/textAreas/items/properties/y/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err96];
                } else {
                  vErrors.push(err96);
                }
                errors++;
              }
            }
            if (data27.w !== undefined) {
              let data32 = data27.w;
              if (typeof data32 == 'number') {
                if (data32 <= 0 || isNaN(data32)) {
                  const err97 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/w',
                    schemaPath: '#/properties/textAreas/items/properties/w/exclusiveMinimum',
                    keyword: 'exclusiveMinimum',
                    params: { comparison: '>', limit: 0 },
                    message: 'must be > 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err97];
                  } else {
                    vErrors.push(err97);
                  }
                  errors++;
                }
              } else {
                const err98 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/w',
                  schemaPath: '#/properties/textAreas/items/properties/w/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err98];
                } else {
                  vErrors.push(err98);
                }
                errors++;
              }
            }
            if (data27.h !== undefined) {
              let data33 = data27.h;
              if (typeof data33 == 'number') {
                if (data33 <= 0 || isNaN(data33)) {
                  const err99 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/h',
                    schemaPath: '#/properties/textAreas/items/properties/h/exclusiveMinimum',
                    keyword: 'exclusiveMinimum',
                    params: { comparison: '>', limit: 0 },
                    message: 'must be > 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err99];
                  } else {
                    vErrors.push(err99);
                  }
                  errors++;
                }
              } else {
                const err100 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/h',
                  schemaPath: '#/properties/textAreas/items/properties/h/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err100];
                } else {
                  vErrors.push(err100);
                }
                errors++;
              }
            }
            if (data27.fontId !== undefined) {
              let data34 = data27.fontId;
              if (!(data34 === 'sans' || data34 === 'serif')) {
                const err101 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/fontId',
                  schemaPath: '#/properties/textAreas/items/properties/fontId/enum',
                  keyword: 'enum',
                  params: {
                    allowedValues: schema11.properties.textAreas.items.properties.fontId.enum,
                  },
                  message: 'must be equal to one of the allowed values',
                };
                if (vErrors === null) {
                  vErrors = [err101];
                } else {
                  vErrors.push(err101);
                }
                errors++;
              }
            }
            if (data27.fontSize !== undefined) {
              let data35 = data27.fontSize;
              if (typeof data35 == 'number') {
                if (data35 <= 0 || isNaN(data35)) {
                  const err102 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/fontSize',
                    schemaPath: '#/properties/textAreas/items/properties/fontSize/exclusiveMinimum',
                    keyword: 'exclusiveMinimum',
                    params: { comparison: '>', limit: 0 },
                    message: 'must be > 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err102];
                  } else {
                    vErrors.push(err102);
                  }
                  errors++;
                }
              } else {
                const err103 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/fontSize',
                  schemaPath: '#/properties/textAreas/items/properties/fontSize/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err103];
                } else {
                  vErrors.push(err103);
                }
                errors++;
              }
            }
            if (data27.minFontSize !== undefined) {
              let data36 = data27.minFontSize;
              if (typeof data36 == 'number') {
                if (data36 <= 0 || isNaN(data36)) {
                  const err104 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/minFontSize',
                    schemaPath:
                      '#/properties/textAreas/items/properties/minFontSize/exclusiveMinimum',
                    keyword: 'exclusiveMinimum',
                    params: { comparison: '>', limit: 0 },
                    message: 'must be > 0',
                  };
                  if (vErrors === null) {
                    vErrors = [err104];
                  } else {
                    vErrors.push(err104);
                  }
                  errors++;
                }
              } else {
                const err105 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/minFontSize',
                  schemaPath: '#/properties/textAreas/items/properties/minFontSize/type',
                  keyword: 'type',
                  params: { type: 'number' },
                  message: 'must be number',
                };
                if (vErrors === null) {
                  vErrors = [err105];
                } else {
                  vErrors.push(err105);
                }
                errors++;
              }
            }
            if (data27.maxLines !== undefined) {
              let data37 = data27.maxLines;
              if (!(typeof data37 == 'number' && !(data37 % 1) && !isNaN(data37))) {
                const err106 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/maxLines',
                  schemaPath: '#/properties/textAreas/items/properties/maxLines/type',
                  keyword: 'type',
                  params: { type: 'integer' },
                  message: 'must be integer',
                };
                if (vErrors === null) {
                  vErrors = [err106];
                } else {
                  vErrors.push(err106);
                }
                errors++;
              }
              if (typeof data37 == 'number') {
                if (data37 > 2 || isNaN(data37)) {
                  const err107 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/maxLines',
                    schemaPath: '#/properties/textAreas/items/properties/maxLines/maximum',
                    keyword: 'maximum',
                    params: { comparison: '<=', limit: 2 },
                    message: 'must be <= 2',
                  };
                  if (vErrors === null) {
                    vErrors = [err107];
                  } else {
                    vErrors.push(err107);
                  }
                  errors++;
                }
                if (data37 < 1 || isNaN(data37)) {
                  const err108 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/maxLines',
                    schemaPath: '#/properties/textAreas/items/properties/maxLines/minimum',
                    keyword: 'minimum',
                    params: { comparison: '>=', limit: 1 },
                    message: 'must be >= 1',
                  };
                  if (vErrors === null) {
                    vErrors = [err108];
                  } else {
                    vErrors.push(err108);
                  }
                  errors++;
                }
              }
            }
            if (data27.color !== undefined) {
              let data38 = data27.color;
              if (typeof data38 === 'string') {
                if (!pattern1.test(data38)) {
                  const err109 = {
                    instancePath: instancePath + '/textAreas/' + i2 + '/color',
                    schemaPath: '#/definitions/color/pattern',
                    keyword: 'pattern',
                    params: { pattern: '^#[0-9a-fA-F]{6}$' },
                    message: 'must match pattern "' + '^#[0-9a-fA-F]{6}$' + '"',
                  };
                  if (vErrors === null) {
                    vErrors = [err109];
                  } else {
                    vErrors.push(err109);
                  }
                  errors++;
                }
              } else {
                const err110 = {
                  instancePath: instancePath + '/textAreas/' + i2 + '/color',
                  schemaPath: '#/definitions/color/type',
                  keyword: 'type',
                  params: { type: 'string' },
                  message: 'must be string',
                };
                if (vErrors === null) {
                  vErrors = [err110];
                } else {
                  vErrors.push(err110);
                }
                errors++;
              }
            }
          } else {
            const err111 = {
              instancePath: instancePath + '/textAreas/' + i2,
              schemaPath: '#/properties/textAreas/items/type',
              keyword: 'type',
              params: { type: 'object' },
              message: 'must be object',
            };
            if (vErrors === null) {
              vErrors = [err111];
            } else {
              vErrors.push(err111);
            }
            errors++;
          }
        }
      } else {
        const err112 = {
          instancePath: instancePath + '/textAreas',
          schemaPath: '#/properties/textAreas/type',
          keyword: 'type',
          params: { type: 'array' },
          message: 'must be array',
        };
        if (vErrors === null) {
          vErrors = [err112];
        } else {
          vErrors.push(err112);
        }
        errors++;
      }
    }
    if (data.palette !== undefined) {
      let data39 = data.palette;
      if (data39 && typeof data39 == 'object' && !Array.isArray(data39)) {
        if (data39.background === undefined) {
          const err113 = {
            instancePath: instancePath + '/palette',
            schemaPath: '#/properties/palette/required',
            keyword: 'required',
            params: { missingProperty: 'background' },
            message: "must have required property '" + 'background' + "'",
          };
          if (vErrors === null) {
            vErrors = [err113];
          } else {
            vErrors.push(err113);
          }
          errors++;
        }
        if (data39.ink === undefined) {
          const err114 = {
            instancePath: instancePath + '/palette',
            schemaPath: '#/properties/palette/required',
            keyword: 'required',
            params: { missingProperty: 'ink' },
            message: "must have required property '" + 'ink' + "'",
          };
          if (vErrors === null) {
            vErrors = [err114];
          } else {
            vErrors.push(err114);
          }
          errors++;
        }
        if (data39.accent === undefined) {
          const err115 = {
            instancePath: instancePath + '/palette',
            schemaPath: '#/properties/palette/required',
            keyword: 'required',
            params: { missingProperty: 'accent' },
            message: "must have required property '" + 'accent' + "'",
          };
          if (vErrors === null) {
            vErrors = [err115];
          } else {
            vErrors.push(err115);
          }
          errors++;
        }
        if (data39.secondary === undefined) {
          const err116 = {
            instancePath: instancePath + '/palette',
            schemaPath: '#/properties/palette/required',
            keyword: 'required',
            params: { missingProperty: 'secondary' },
            message: "must have required property '" + 'secondary' + "'",
          };
          if (vErrors === null) {
            vErrors = [err116];
          } else {
            vErrors.push(err116);
          }
          errors++;
        }
        for (const key3 in data39) {
          let data40 = data39[key3];
          if (typeof data40 === 'string') {
            if (!pattern1.test(data40)) {
              const err117 = {
                instancePath:
                  instancePath + '/palette/' + key3.replace(/~/g, '~0').replace(/\//g, '~1'),
                schemaPath: '#/definitions/color/pattern',
                keyword: 'pattern',
                params: { pattern: '^#[0-9a-fA-F]{6}$' },
                message: 'must match pattern "' + '^#[0-9a-fA-F]{6}$' + '"',
              };
              if (vErrors === null) {
                vErrors = [err117];
              } else {
                vErrors.push(err117);
              }
              errors++;
            }
          } else {
            const err118 = {
              instancePath:
                instancePath + '/palette/' + key3.replace(/~/g, '~0').replace(/\//g, '~1'),
              schemaPath: '#/definitions/color/type',
              keyword: 'type',
              params: { type: 'string' },
              message: 'must be string',
            };
            if (vErrors === null) {
              vErrors = [err118];
            } else {
              vErrors.push(err118);
            }
            errors++;
          }
        }
      } else {
        const err119 = {
          instancePath: instancePath + '/palette',
          schemaPath: '#/properties/palette/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        };
        if (vErrors === null) {
          vErrors = [err119];
        } else {
          vErrors.push(err119);
        }
        errors++;
      }
    }
    if (data.layers !== undefined) {
      let data41 = data.layers;
      if (data41 && typeof data41 == 'object' && !Array.isArray(data41)) {
        if (data41.background === undefined) {
          const err120 = {
            instancePath: instancePath + '/layers',
            schemaPath: '#/properties/layers/required',
            keyword: 'required',
            params: { missingProperty: 'background' },
            message: "must have required property '" + 'background' + "'",
          };
          if (vErrors === null) {
            vErrors = [err120];
          } else {
            vErrors.push(err120);
          }
          errors++;
        }
        if (data41.foreground === undefined) {
          const err121 = {
            instancePath: instancePath + '/layers',
            schemaPath: '#/properties/layers/required',
            keyword: 'required',
            params: { missingProperty: 'foreground' },
            message: "must have required property '" + 'foreground' + "'",
          };
          if (vErrors === null) {
            vErrors = [err121];
          } else {
            vErrors.push(err121);
          }
          errors++;
        }
        if (data41.background !== undefined) {
          if (typeof data41.background !== 'string') {
            const err122 = {
              instancePath: instancePath + '/layers/background',
              schemaPath: '#/properties/layers/properties/background/type',
              keyword: 'type',
              params: { type: 'string' },
              message: 'must be string',
            };
            if (vErrors === null) {
              vErrors = [err122];
            } else {
              vErrors.push(err122);
            }
            errors++;
          }
        }
        if (data41.foreground !== undefined) {
          if (typeof data41.foreground !== 'string') {
            const err123 = {
              instancePath: instancePath + '/layers/foreground',
              schemaPath: '#/properties/layers/properties/foreground/type',
              keyword: 'type',
              params: { type: 'string' },
              message: 'must be string',
            };
            if (vErrors === null) {
              vErrors = [err123];
            } else {
              vErrors.push(err123);
            }
            errors++;
          }
        }
      } else {
        const err124 = {
          instancePath: instancePath + '/layers',
          schemaPath: '#/properties/layers/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        };
        if (vErrors === null) {
          vErrors = [err124];
        } else {
          vErrors.push(err124);
        }
        errors++;
      }
    }
    if (data.thumbnail !== undefined) {
      if (typeof data.thumbnail !== 'string') {
        const err125 = {
          instancePath: instancePath + '/thumbnail',
          schemaPath: '#/properties/thumbnail/type',
          keyword: 'type',
          params: { type: 'string' },
          message: 'must be string',
        };
        if (vErrors === null) {
          vErrors = [err125];
        } else {
          vErrors.push(err125);
        }
        errors++;
      }
    }
    if (data.licenses !== undefined) {
      let data45 = data.licenses;
      if (Array.isArray(data45)) {
        if (data45.length < 1) {
          const err126 = {
            instancePath: instancePath + '/licenses',
            schemaPath: '#/properties/licenses/minItems',
            keyword: 'minItems',
            params: { limit: 1 },
            message: 'must NOT have fewer than 1 items',
          };
          if (vErrors === null) {
            vErrors = [err126];
          } else {
            vErrors.push(err126);
          }
          errors++;
        }
        const len3 = data45.length;
        for (let i3 = 0; i3 < len3; i3++) {
          if (typeof data45[i3] !== 'string') {
            const err127 = {
              instancePath: instancePath + '/licenses/' + i3,
              schemaPath: '#/properties/licenses/items/type',
              keyword: 'type',
              params: { type: 'string' },
              message: 'must be string',
            };
            if (vErrors === null) {
              vErrors = [err127];
            } else {
              vErrors.push(err127);
            }
            errors++;
          }
        }
      } else {
        const err128 = {
          instancePath: instancePath + '/licenses',
          schemaPath: '#/properties/licenses/type',
          keyword: 'type',
          params: { type: 'array' },
          message: 'must be array',
        };
        if (vErrors === null) {
          vErrors = [err128];
        } else {
          vErrors.push(err128);
        }
        errors++;
      }
    }
  } else {
    const err129 = {
      instancePath,
      schemaPath: '#/type',
      keyword: 'type',
      params: { type: 'object' },
      message: 'must be object',
    };
    if (vErrors === null) {
      vErrors = [err129];
    } else {
      vErrors.push(err129);
    }
    errors++;
  }
  validate10.errors = vErrors;
  return errors === 0;
}
