import type { FrameDefinition, SlotDefinition } from '../core/types';
export const slot = (
  order: number,
  x: number,
  y: number,
  w: number,
  h: number,
  shape: SlotDefinition['shape'] = 'roundedRect',
  options: Partial<SlotDefinition> = {},
): SlotDefinition => ({
  id: `p${order}`,
  order,
  x,
  y,
  w,
  h,
  shape,
  radius: 55,
  rotationDeg: 0,
  matteColor: '#f2efe9',
  ...options,
});
export function frame(
  id: string,
  name: string,
  format: 'strip' | 'card',
  categories: string[],
  colors: string[],
  slots: SlotDefinition[],
  description: string,
  serif = false,
): FrameDefinition {
  const version = 2;
  const base = `/frames/${id}/v${version}`;
  return {
    id,
    name,
    version,
    format,
    categories,
    designWidth: format === 'strip' ? 1200 : 1800,
    designHeight: format === 'strip' ? 3600 : 2700,
    slots,
    description,
    palette: { background: colors[0], ink: colors[1], accent: colors[2], secondary: colors[3] },
    layers: { background: `${base}/background.svg`, foreground: `${base}/foreground.svg` },
    thumbnail: `${base}/thumbnail.png`,
    licenses: [
      'Original vector artwork © Fotbooth contributors. CC0-1.0.',
      'DM Sans and Fraunces: SIL Open Font License 1.1.',
    ],
    textAreas: [
      {
        id: 'title',
        text: name,
        x: 0.06,
        y: 0.012,
        w: 0.88,
        h: 0.036,
        fontId: serif ? 'serif' : 'sans',
        fontSize: format === 'strip' ? 100 : 94,
        minFontSize: 48,
        maxLines: 1,
        color: colors[1],
      },
      {
        id: 'caption',
        x: 0.07,
        y: 0.906,
        w: 0.86,
        h: 0.055,
        fontId: serif ? 'serif' : 'sans',
        fontSize: 60,
        minFontSize: 32,
        maxLines: 2,
        color: colors[1],
      },
      {
        id: 'date',
        x: 0.15,
        y: 0.972,
        w: 0.7,
        h: 0.018,
        fontId: 'sans',
        fontSize: 34,
        minFontSize: 26,
        maxLines: 1,
        color: colors[1],
      },
    ],
  };
}
