import fs from 'node:fs/promises';
import Ajv from 'ajv';
import standaloneModule from 'ajv/dist/standalone/index.js';
import { format } from 'prettier';

const schema = JSON.parse(
  await fs.readFile(new URL('../src/frames/schema.json', import.meta.url), 'utf8'),
);
const ajv = new Ajv({ allErrors: true, strict: false, code: { source: true, esm: true } });
const standalone = standaloneModule.default ?? standaloneModule;
let source = standalone(ajv, ajv.compile(schema));
// The only runtime helper in this schema counts Unicode code points. Keep the
// generated ES module self-contained, so neither CommonJS nor Ajv runs in-browser.
source = source.replaceAll(
  'require("ajv/dist/runtime/ucs2length").default',
  '((value) => Array.from(value).length)',
);
if (/\brequire\(/.test(source)) throw new Error('Unexpected standalone schema runtime dependency');
source = await format(
  '// Generated by npm run schema:build; edit schema.json instead.\n' + source,
  { parser: 'babel', singleQuote: true, printWidth: 100 },
);
const target = new URL('../src/frames/compiled-schema.js', import.meta.url);
const previous = await fs.readFile(target, 'utf8').catch(() => null);
if (previous !== source) await fs.writeFile(target, source);
console.log('Compiled browser schema validator without runtime code generation.');
